plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-2.1.1.cjs

packageExtensions:
  '@apollographql/apollo-tools@*':
    peerDependencies:
      'graphql': '*'
  '@apollo/client@*':
    dependencies:
      'react-dom': '*'
  'graphql-middleware@*':
    peerDependencies:
      'graphql': '*'
  'graphql-subscriptions@*':
    peerDependencies:
      'graphql': '*'
  'graphql-upload@*':
    peerDependencies:
      'graphql': '*'
  'next@*':
    dependencies:
      'caniuse-lite': '*'
