packageExtensions:
  "@apollo/client@*":
    dependencies:
      react-dom: "*"
  "@apollographql/apollo-tools@*":
    peerDependencies:
      graphql: "*"
  graphql-middleware@*:
    peerDependencies:
      graphql: "*"
  graphql-subscriptions@*:
    peerDependencies:
      graphql: "*"
  graphql-upload@*:
    peerDependencies:
      graphql: "*"
  next@*:
    dependencies:
      caniuse-lite: "*"
  node-fetch@*:
    dependencies:
      "encoding": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.1.1.cjs
