version: "3"
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      NODE_ENV: development
  mongo:
    image: mongo:latest
    # volumes:
    #   - ./data:/data/db
    ports:
      - "27017:27017"
