version: '3.4'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    depends_on:
      - db
    ports:
      - '${WEB_PORT:-3000}:3000'
    volumes:
      - ./server:/usr/src/app/server
      - ./client:/usr/src/app/client
      - ./.babelrc:/usr/src/app/.babelrc
      - ./next.config.js:/usr/src/app/next.config.js
      - ./postcss.config.js:/usr/src/app/postcss.config.js
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./jest.config.js:/usr/src/app/jest.config.js
      - ./jest.setup.js:/usr/src/app/jest.setup.js
      - ./__mocks__:/usr/src/app/__mocks__
      - ./__tests__:/usr/src/app/__tests__
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGO_URI: mongodb://db:27017/schooled-lunch
      EMAIL_FROM: no-reply@schooledlunch.club
    stdin_open: true
    tty: true
  db:
    image: mongo:latest
    volumes:
      - dbdata:/data/db
    ports:
      - '27017:27017'
volumes:
  ? dbdata
