component: express
org: studiodrishti
app: recipe-lab
name: recipe-lab-api

inputs:
  src: ./
  # src:
  #   src: ./
  #   hook: yarn build
  #   dist: ./dist
  env:
    DATABASE_URL: ${env:DATABASE_URL}
    NODE_ENV: production
  domain: api.recipelab.io
  region: us-west-2
  vpc:
    securityGroupIds:
      - sg-1318933a
    subnetIds:
      - subnet-afb5eb84
      - subnet-e935c4a3
