component: express
org: studiodrishti
app: recipe-lab
name: recipe-lab-api

inputs:
  src: ./
  # src:
  #   src: ./
  #   hook: yarn build
  #   dist: ./dist
  env:
    DATABASE_URL: ${env:DATABASE_URL}
    NODE_ENV: production
  domain: api.recipelab.io
  region: us-west-2
  # vpc:
  #   securityGroupIds:
  #     -
  #   subnetIds:
  #     -
