name: Deploy

on: pull_request

env:
  SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

defaults:
  runs-on: ubuntu-latest

jobs:
  api:
    defaults:
      run:
        working-directory: packages/api
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
          working-directory: packages/api
      - name: generate prisma client
        run: npm run prisma:generate
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy
