name: Deploy

on: pull_request

env:
  SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "packages/api"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - name: install dependencies
        run: npm install --production --no-optional --no-package-lock
      - name: prisma generate
        run: npm run prisma:generate
      - name: serverless deploy
        run: npm run deploy
