name: Deploy

on: pull_request

env:
  SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
          working-directory: packages/api
      - name: serverless deploy
        uses: serverless/github-action@v1.53.0
        with:
          args: deploy
          working-directory: packages/api
